/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy
 * Langsch - fernanda.langsch@tum.de
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#include "simple_msgs/float.hpp"
#include "simple_msgs/generated/float_generated.h"

// Specialized functions for NumericType<float>.

namespace simple_msgs {

/**
 * @brief Construct a Float message using a raw memory coming from network.
 */
template <>
NumericType<float>::NumericType(const void* data) : data_{GetFloatFbs(data)->data()} {}

/**
 * @brief Copy assignment operator that uses raw memory coming from the network.
 */
template <>
NumericType<float>& NumericType<float>::operator=(std::shared_ptr<void*> rhs) {
  data_.store(GetFloatFbs(*rhs)->data());
  return *this;
}

/**
 * @brief Builds and returns the buffer accordingly to the value currently stored.
 */
template <>
std::shared_ptr<flatbuffers::DetachedBuffer> NumericType<float>::getBufferData() const {
  flatbuffers::FlatBufferBuilder builder{1024};
  FloatFbsBuilder tmp_builder{builder};
  tmp_builder.add_data(data_.load());
  FinishFloatFbsBuffer(builder, tmp_builder.Finish());
  return std::make_shared<flatbuffers::DetachedBuffer>(builder.Release());
}

/**
 * @brief Returns an identifier of the message type generated by the flatbuffers.
 */
template <>
std::string NumericType<float>::getTopic() {
  return FloatFbsIdentifier();
}

}  // Namespace simple_msgs.
