/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy
 * Langsch - fernanda.langsch@tum.de
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#include "simple_msgs/int.hpp"
#include "simple_msgs/generated/int_generated.h"

// Specialized functions for NumericType<int>.

namespace simple_msgs {

/**
 * @brief Construct a Float message using a raw memory coming from network.
 */
template <>
NumericType<int>::NumericType(const void* data) : data_{GetIntFbs(data)->data()} {}

/**
 * @brief Copy assignment operator that uses raw memory coming from the network.
 */
template <>
NumericType<int>& NumericType<int>::operator=(std::shared_ptr<void*> rhs) {
  data_.store(GetIntFbs(*rhs)->data());
  return *this;
}

/**
 * @brief Builds and returns the buffer accordingly to the value currently stored.
 */
template <>
std::shared_ptr<flatbuffers::DetachedBuffer> NumericType<int>::getBufferData() const {
  flatbuffers::FlatBufferBuilder builder{1024};
  IntFbsBuilder tmp_builder{builder};
  tmp_builder.add_data(data_.load());
  FinishIntFbsBuffer(builder, tmp_builder.Finish());
  return std::make_shared<flatbuffers::DetachedBuffer>(builder.Release());
}

/**
 * @brief Returns an identifier of the message type generated by the flatbuffers.
 */
template <>
std::string NumericType<int>::getTopic() {
  return IntFbsIdentifier();
}

}  // Namespace simple_msgs.
