image: ubuntu-simple

stages:
  - build
  - test

################# Building

build_msvc15:
  stage: build
  tags:
    - windows
  script:
    - cd ..
    - IF NOT EXIST "simple_msvs15" mkdir "simple_msvs15"
    - cd simple_msvs15
    - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_TESTS=ON ../simple
    - cmake --build . --clean-first --config Release

build_msvc17:
  stage: build
  tags:
    - windows
  script:
    - cd ..
    - IF NOT EXIST "simple_msvs17" mkdir "simple_msvs17"
    - cd simple_msvs17
    - cmake -G "Visual Studio 15 2017 Win64" -DBUILD_TESTS=ON ../simple
    - cmake --build . --clean-first --config Release
    
build_clang:
  stage: build
  tags:
    - linux
    - clang
  script:
    - mkdir -p simple_clang
    - cd simple_clang
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release ..
    - make
  cache:
    key: clang_cache
    paths:
      - simple_clang/
  artifacts:
    paths:
    - simple_clang/

build_gcc:
  stage: build
  tags:
    - linux
    - g++
  script:
    - mkdir -p simple_gcc
    - cd simple_gcc
    - cmake -DCMAKE_CXX_COMPILER=g++ -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release ..
    - make
  cache:
    key: gcc_cache
    paths:
      - simple_gcc/
  artifacts:
    paths:
    - simple_gcc/

    
################# Testing

test_msvs15:
    stage : test
    dependencies:
      - build_msvc15
    tags:
      - windows
    script:
      - cd ../simple_msvs15
      - ctest -R simple_tests -C Release --output-on-failure

test_msvs17:
    stage : test
    dependencies:
      - build_msvc17
    tags:
      - windows
    script:
      - cd ../simple_msvs17
      - ctest -R simple_tests -C Release --output-on-failure
      
test_gcc:
    stage : test
    dependencies:
      - build_gcc
    tags:
      - linux
      - gcc
    script:
      - cd simple_gcc
      - ctest -R simple_tests --output-on-failure
      - gcovr -e 'tests/include/*' -e 'msgs/include/simple_msgs/generated/*' -r ..
     
test_clang:
    stage : test
    dependencies:
      - build_clang
    tags:
      - linux
      - clang
    script:
      - cd simple_clang
      - ctest -R simple_tests --output-on-failure
