image: ubuntu-simple

stages:
  - build
  - test

variables:
  ZEROMQ_DIR_2015: "C:/Program Files/ZeroMQ_2015"
  ZEROMQ_DIR_2017: "C:/Program Files/ZeroMQ_2017"
  ZEROMQ_2015: "-DZeroMQ_INCLUDE_DIR=%ZEROMQ_DIR_2015%/include -DZeroMQ_LIBRARY=%ZEROMQ_DIR_2015%/lib/libzmq-v140-mt-4_2_4.lib"
  ZEROMQ_2017: "-DZeroMQ_INCLUDE_DIR=%ZEROMQ_DIR_2017%/include -DZeroMQ_LIBRARY=%ZEROMQ_DIR_2017%/lib/libzmq-v141-mt-4_2_4.lib"
  VS150COMNTOOLS: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/Tools/"

################# Building

build_msvc15:
  stage: build
  tags:
    - windows
  script:
    - IF NOT EXIST "simple_msvs15" mkdir "simple_msvs15"
    - cd simple_msvs15
    - "@call ""%VS140COMNTOOLS%VsDevCmd.bat"""
    - cmake -G "Visual Studio 14 2015 Win64" %ZEROMQ_2015% -DBUILD_TESTS=ON ..
    - devenv /build Release simple.sln
  cache:
    key: msvs15_cache
    paths:
      - simple_msvs15/
  artifacts:
    paths:
    - simple_msvs15/

build_msvc17:
  stage: build
  tags:
    - windows
  script:
    - IF NOT EXIST "simple_msvs17" mkdir "simple_msvs17"
    - cd simple_msvs17
    - "@call ""%VS150COMNTOOLS%VsDevCmd.bat"""
    - cmake -G "Visual Studio 15 2017 Win64" %ZEROMQ_2017% -DBUILD_TESTS=ON ..
    - devenv /build Release simple.sln
  cache:
    key: msvs17_cache
    paths:
      - simple_msvs17/
  artifacts:
    paths:
    - simple_msvs17/
    
build_gcc:
  stage: build
  tags:
    - linux
    - g++
  script:
    - mkdir -p simple_gcc
    - cd simple_gcc
    - cmake -DCMAKE_CXX_COMPILER=g++ -DBUILD_TESTS=ON ..
    - make
  cache:
    key: gcc_cache
    paths:
      - simple_gcc/
  artifacts:
    paths:
    - simple_gcc/
    
build_clang:
  stage: build
  tags:
    - linux
    - clang
  script:
    - mkdir -p simple_clang
    - cd simple_clang
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTS=ON ..
    - make
  cache:
    key: clang_cache
    paths:
      - simple_clang/
  artifacts:
    paths:
    - simple_clang/

################# Testing

test_msvs15:
    stage : test
    dependencies:
      - build_msvc15
    tags:
      - windows
    script:
      - cd simple_msvs15
      - copy .\msgs\Release\libsimple_msgs.dll .\tests\Release\libsimple_msgs.dll
      - ctest -R simple_tests -C Release --output-on-failure

test_msvs17:
    stage : test
    dependencies:
      - build_msvc17
    tags:
      - windows
    script:
      - cd simple_msvs17
      - copy .\msgs\Release\libsimple_msgs.dll .\tests\Release\libsimple_msgs.dll
      - ctest -R simple_tests -C Release --output-on-failure
      
test_gcc:
    stage : test
    dependencies:
      - build_gcc
    tags:
      - linux
      - gcc
    script:
      - cd simple_gcc
      - ctest -R simple_tests --output-on-failure
     
test_clang:
    stage : test
    dependencies:
      - build_clang
    tags:
      - linux
      - clang
    script:
      - cd simple_clang
      - ctest -R simple_tests --output-on-failure