# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2017

skip_tags: true

configuration:
  - Debug
  - Release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 140
      VISUAL_STUDIO_VERSION: 14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
      VISUAL_STUDIO_INTERNAL_VERSION: 141
      VISUAL_STUDIO_VERSION: 14.1

matrix:
  fast_finish: true

install:
  - mkdir deps && cd deps
  - git clone https://github.com/google/flatbuffers.git # Checkout master (for the moment)
  - cd flatbuffers && mkdir flatbuffer_build && cd flatbuffer_build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
  - cmake --build . --target install --config %CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%/deps
  - git clone https://github.com/zeromq/libzmq.git # Checkout master (for the moment)
  - cd libzmq && mkdir libzmq_build && cd libzmq_build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DZMQ_BUILD_TESTS=OFF ..
  - cmake --build . --target install --config %CONFIGURATION%

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - rmdir deps /s /q
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DSIMPLE_BUILD_TESTS=ON -DSIMPLE_BUILD_EXAMPLES=ON ..

build_script:
  - cmake --build . --config %CONFIGURATION% -- /verbosity:minimal

test_script:
  - ctest -R simple_tests -C %CONFIGURATION% --output-on-failure
