# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2017

configuration:
  - Release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 140
      VISUAL_STUDIO_VERSION: 14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
      VISUAL_STUDIO_INTERNAL_VERSION: 141
      VISUAL_STUDIO_VERSION: 14.1

matrix:
  fast_finish: true

install:
  - mkdir deps && cd deps
  - git clone -b v3.11.4 --single-branch https://github.com/protocolbuffers/protobuf.git # Fixed to release 3.11.4
  - cd protobuf && mkdir protobuf_install && mkdir protobuf_build && cd protobuf_build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DCMAKE_INSTALL_PREFIX=../protobuf_install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_SHARED_LIBS=OFF ../cmake
  - cmake --build . --target install --config %CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%/deps
  - git clone -b v4.3.2 --single-branch https://github.com/zeromq/libzmq.git # Fixed to release 4.3.2
  - cd libzmq && mkdir libzmq_build && cd libzmq_build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DENABLE_CURVE=OFF -DZMQ_BUILD_TESTS=OFF ..
  - cmake --build . --target install --config %CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%/deps
  - git clone -b v4.6.0 --single-branch https://github.com/zeromq/cppzmq.git # Fixed to release 4.6.0
  - cd cppzmq && mkdir cppzmq_build && cd cppzmq_build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DCPPZMQ_BUILD_TESTS=OFF ..
  - cmake --build . --target install --config %CONFIGURATION%

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - rmdir deps /s /q
  - mkdir build && cd build
  - ps: >-
      If ($env:APPVEYOR_REPO_TAG -eq "false") {
        cmake -G "$env:CMAKE_GENERATOR Win64" -DProtobuf_DIR=%APPVEYOR_BUILD_FOLDER%/deps/protobuf/protobuf_install -DSIMPLE_BUILD_TESTS=ON -DSIMPLE_BUILD_EXAMPLES=ON ..
      } Else {
        cmake -G "$env:CMAKE_GENERATOR Win64" -DProtobuf_DIR=%APPVEYOR_BUILD_FOLDER%/deps/protobuf/protobuf_install -DSIMPLE_BUILD_STATIC=OFF -DSIMPLE_ENABLE_CPACK=ON ..
      }

build_script:
  - cmake --build . --config %CONFIGURATION% -- /verbosity:minimal

test_script:
  - ps: >-
      If ($env:APPVEYOR_REPO_TAG -eq "false") { 
        ctest -R simple_tests -C $env:CONFIGURATION --output-on-failure
      }

after_build:
  - ps: >-
      If ($env:APPVEYOR_REPO_TAG -eq "true") { 
        cpack
      }

artifacts:
- path: 'build/*.exe'
  name: simple_artifact

deploy:
  description: 'S.I.M.P.L.E. Release'
  provider: GitHub
  auth_token:
    secure: /Zfum05XMUCPaLKLsrsOTr/t4A8Kvz3lDN4ajPt6SZRlU+AX1/ee0CqpgR5AKCGg
  artifact: simple_artifact
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
