jobs:
  - job: win_vs2017
    displayName: Windows Visual Studio 2017
    timeoutInMinutes: 0
    variables:
      BUILD_DIR: '$(Agent.WorkFolder)\build'
      VCPKG_DIR: '$(Agent.WorkFolder)\vcpkg'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      PLATFORM: x64
      ARCHITECTURE: 'x86_amd64'
      GENERATOR: 'Visual Studio 15 2017 Win64'
    strategy:
      maxParallel: 8
      matrix:
        Release:
          configuration: Release
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - script: |
          git clone https://github.com/microsoft/vcpkg --depth 1 %VCPKG_DIR%
          echo.set(VCPKG_BUILD_TYPE release)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
          %VCPKG_DIR%\bootstrap-vcpkg.bat
          %VCPKG_DIR%\vcpkg.exe version
        displayName: 'Bootstrap vcpkg'
      - script: |
          %VCPKG_DIR%\vcpkg.exe install flatbuffers zeromq --triplet %PLATFORM%-windows && %VCPKG_DIR%\vcpkg.exe list
        displayName: 'Install Dependencies'
      - script: |
          rmdir %VCPKG_DIR%\downloads /S /Q
          rmdir %VCPKG_DIR%\packages /S /Q
        displayName: 'Free Up Space'
      - script: |
          call "%VCVARSALL%" %ARCHITECTURE%
          set PATH=%VCPKG_DIR%\installed\%PLATFORM%-windows\bin;%PATH%
          mkdir %BUILD_DIR% && cd %BUILD_DIR%
          cmake $(Build.SourcesDirectory) -G"%GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake -DVCPKG_APPLOCAL_DEPS=ON -DSIMPLE_BUILD_TESTS=ON -DSIMPLE_BUILD_EXAMPLES=ON
        displayName: 'CMake Configuration'
      - script: cd %BUILD_DIR% && cmake --build . --config %CONFIGURATION%
        displayName: 'Build Library'
      - script: cd %BUILD_DIR% && ctest -R simple_tests -C %CONFIGURATION% --output-on-failure
        displayName: 'Run Unit Tests'