// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERICBOOL_SIMPLE_H_
#define FLATBUFFERS_GENERATED_GENERICBOOL_SIMPLE_H_

#include "flatbuffers/flatbuffers.h"

#include "header_generated.h"

namespace simple {

struct generic_bool;

struct generic_bool FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_DATA = 4,
    VT_HEADER = 6
  };
  bool data() const {
    return GetField<uint8_t>(VT_DATA, 0) != 0;
  }
  const header *Header() const {
    return GetPointer<const header *>(VT_HEADER);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DATA) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(Header()) &&
           verifier.EndTable();
  }
};

struct generic_boolBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(bool data) {
    fbb_.AddElement<uint8_t>(generic_bool::VT_DATA, static_cast<uint8_t>(data), 0);
  }
  void add_Header(flatbuffers::Offset<header> Header) {
    fbb_.AddOffset(generic_bool::VT_HEADER, Header);
  }
  explicit generic_boolBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  generic_boolBuilder &operator=(const generic_boolBuilder &);
  flatbuffers::Offset<generic_bool> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<generic_bool>(end);
    return o;
  }
};

inline flatbuffers::Offset<generic_bool> Creategeneric_bool(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool data = false,
    flatbuffers::Offset<header> Header = 0) {
  generic_boolBuilder builder_(_fbb);
  builder_.add_Header(Header);
  builder_.add_data(data);
  return builder_.Finish();
}

inline const simple::generic_bool *Getgeneric_bool(const void *buf) {
  return flatbuffers::GetRoot<simple::generic_bool>(buf);
}

inline const char *generic_boolIdentifier() {
  return "BOOL";
}

inline bool generic_boolBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, generic_boolIdentifier());
}

inline bool Verifygeneric_boolBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<simple::generic_bool>(generic_boolIdentifier());
}

inline void Finishgeneric_boolBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<simple::generic_bool> root) {
  fbb.Finish(root, generic_boolIdentifier());
}

}  // namespace simple

#endif  // FLATBUFFERS_GENERATED_GENERICBOOL_SIMPLE_H_
