// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERICSTRING_SIMPLE_H_
#define FLATBUFFERS_GENERATED_GENERICSTRING_SIMPLE_H_

#include "flatbuffers/flatbuffers.h"

#include "header_generated.h"

namespace simple {

struct generic_string;

struct generic_string FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_DATA = 4,
    VT_HEADER = 6
  };
  const flatbuffers::String *data() const {
    return GetPointer<const flatbuffers::String *>(VT_DATA);
  }
  const header *Header() const {
    return GetPointer<const header *>(VT_HEADER);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.Verify(data()) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(Header()) &&
           verifier.EndTable();
  }
};

struct generic_stringBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(flatbuffers::Offset<flatbuffers::String> data) {
    fbb_.AddOffset(generic_string::VT_DATA, data);
  }
  void add_Header(flatbuffers::Offset<header> Header) {
    fbb_.AddOffset(generic_string::VT_HEADER, Header);
  }
  explicit generic_stringBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  generic_stringBuilder &operator=(const generic_stringBuilder &);
  flatbuffers::Offset<generic_string> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<generic_string>(end);
    return o;
  }
};

inline flatbuffers::Offset<generic_string> Creategeneric_string(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> data = 0,
    flatbuffers::Offset<header> Header = 0) {
  generic_stringBuilder builder_(_fbb);
  builder_.add_Header(Header);
  builder_.add_data(data);
  return builder_.Finish();
}

inline flatbuffers::Offset<generic_string> Creategeneric_stringDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *data = nullptr,
    flatbuffers::Offset<header> Header = 0) {
  return simple::Creategeneric_string(
      _fbb,
      data ? _fbb.CreateString(data) : 0,
      Header);
}

inline const simple::generic_string *Getgeneric_string(const void *buf) {
  return flatbuffers::GetRoot<simple::generic_string>(buf);
}

inline const char *generic_stringIdentifier() {
  return "STRG";
}

inline bool generic_stringBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, generic_stringIdentifier());
}

inline bool Verifygeneric_stringBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<simple::generic_string>(generic_stringIdentifier());
}

inline void Finishgeneric_stringBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<simple::generic_string> root) {
  fbb.Finish(root, generic_stringIdentifier());
}

}  // namespace simple

#endif  // FLATBUFFERS_GENERATED_GENERICSTRING_SIMPLE_H_
