// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERICINT_SIMPLE_MSGS_H_
#define FLATBUFFERS_GENERATED_GENERICINT_SIMPLE_MSGS_H_

#include "flatbuffers/flatbuffers.h"

namespace simple_msgs {

struct generic_int;

struct generic_int FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_DATA = 4,
    VT_HEADER = 6
  };
  int32_t data() const {
    return GetField<int32_t>(VT_DATA, 0);
  }
  uint8_t Header() const {
    return GetField<uint8_t>(VT_HEADER, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_DATA) &&
           VerifyField<uint8_t>(verifier, VT_HEADER) &&
           verifier.EndTable();
  }
};

struct generic_intBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(int32_t data) {
    fbb_.AddElement<int32_t>(generic_int::VT_DATA, data, 0);
  }
  void add_Header(uint8_t Header) {
    fbb_.AddElement<uint8_t>(generic_int::VT_HEADER, Header, 0);
  }
  explicit generic_intBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  generic_intBuilder &operator=(const generic_intBuilder &);
  flatbuffers::Offset<generic_int> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<generic_int>(end);
    return o;
  }
};

inline flatbuffers::Offset<generic_int> Creategeneric_int(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t data = 0,
    uint8_t Header = 0) {
  generic_intBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_Header(Header);
  return builder_.Finish();
}

inline const simple_msgs::generic_int *Getgeneric_int(const void *buf) {
  return flatbuffers::GetRoot<simple_msgs::generic_int>(buf);
}

inline const char *generic_intIdentifier() {
  return "INTG";
}

inline bool generic_intBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, generic_intIdentifier());
}

inline bool Verifygeneric_intBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<simple_msgs::generic_int>(generic_intIdentifier());
}

inline void Finishgeneric_intBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<simple_msgs::generic_int> root) {
  fbb.Finish(root, generic_intIdentifier());
}

}  // namespace simple_msgs

#endif  // FLATBUFFERS_GENERATED_GENERICINT_SIMPLE_MSGS_H_
