// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERICDOUBLE_SIMPLE_MSGS_H_
#define FLATBUFFERS_GENERATED_GENERICDOUBLE_SIMPLE_MSGS_H_

#include "flatbuffers/flatbuffers.h"

namespace simple_msgs {

struct generic_double;

struct generic_double FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_DATA = 4,
    VT_HEADER = 6
  };
  double data() const {
    return GetField<double>(VT_DATA, 0.0);
  }
  uint8_t Header() const {
    return GetField<uint8_t>(VT_HEADER, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_DATA) &&
           VerifyField<uint8_t>(verifier, VT_HEADER) &&
           verifier.EndTable();
  }
};

struct generic_doubleBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(double data) {
    fbb_.AddElement<double>(generic_double::VT_DATA, data, 0.0);
  }
  void add_Header(uint8_t Header) {
    fbb_.AddElement<uint8_t>(generic_double::VT_HEADER, Header, 0);
  }
  explicit generic_doubleBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  generic_doubleBuilder &operator=(const generic_doubleBuilder &);
  flatbuffers::Offset<generic_double> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<generic_double>(end);
    return o;
  }
};

inline flatbuffers::Offset<generic_double> Creategeneric_double(
    flatbuffers::FlatBufferBuilder &_fbb,
    double data = 0.0,
    uint8_t Header = 0) {
  generic_doubleBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_Header(Header);
  return builder_.Finish();
}

inline const simple_msgs::generic_double *Getgeneric_double(const void *buf) {
  return flatbuffers::GetRoot<simple_msgs::generic_double>(buf);
}

inline const char *generic_doubleIdentifier() {
  return "DOBL";
}

inline bool generic_doubleBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, generic_doubleIdentifier());
}

inline bool Verifygeneric_doubleBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<simple_msgs::generic_double>(generic_doubleIdentifier());
}

inline void Finishgeneric_doubleBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<simple_msgs::generic_double> root) {
  fbb.Finish(root, generic_doubleIdentifier());
}

}  // namespace simple_msgs

#endif  // FLATBUFFERS_GENERATED_GENERICDOUBLE_SIMPLE_MSGS_H_
