// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HEADER_SIMPLE_MSGS_H_
#define FLATBUFFERS_GENERATED_HEADER_SIMPLE_MSGS_H_

#include "flatbuffers/flatbuffers.h"

namespace simple_msgs {

struct header;

struct header FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SEQUENCE = 4,
    VT_FRAME_ID = 6,
    VT_TIMESTAMP = 8
  };
  int32_t sequence() const {
    return GetField<int32_t>(VT_SEQUENCE, 0);
  }
  const flatbuffers::String *frame_id() const {
    return GetPointer<const flatbuffers::String *>(VT_FRAME_ID);
  }
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SEQUENCE) &&
           VerifyOffset(verifier, VT_FRAME_ID) &&
           verifier.Verify(frame_id()) &&
           VerifyField<double>(verifier, VT_TIMESTAMP) &&
           verifier.EndTable();
  }
};

struct headerBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_sequence(int32_t sequence) {
    fbb_.AddElement<int32_t>(header::VT_SEQUENCE, sequence, 0);
  }
  void add_frame_id(flatbuffers::Offset<flatbuffers::String> frame_id) {
    fbb_.AddOffset(header::VT_FRAME_ID, frame_id);
  }
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(header::VT_TIMESTAMP, timestamp, 0.0);
  }
  explicit headerBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  headerBuilder &operator=(const headerBuilder &);
  flatbuffers::Offset<header> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<header>(end);
    return o;
  }
};

inline flatbuffers::Offset<header> Createheader(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t sequence = 0,
    flatbuffers::Offset<flatbuffers::String> frame_id = 0,
    double timestamp = 0.0) {
  headerBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_frame_id(frame_id);
  builder_.add_sequence(sequence);
  return builder_.Finish();
}

inline flatbuffers::Offset<header> CreateheaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t sequence = 0,
    const char *frame_id = nullptr,
    double timestamp = 0.0) {
  return simple_msgs::Createheader(
      _fbb,
      sequence,
      frame_id ? _fbb.CreateString(frame_id) : 0,
      timestamp);
}

inline const simple_msgs::header *Getheader(const void *buf) {
  return flatbuffers::GetRoot<simple_msgs::header>(buf);
}

inline bool VerifyheaderBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<simple_msgs::header>(nullptr);
}

inline void FinishheaderBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<simple_msgs::header> root) {
  fbb.Finish(root);
}

}  // namespace simple_msgs

#endif  // FLATBUFFERS_GENERATED_HEADER_SIMPLE_MSGS_H_
