# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget simple simple_msgs)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target simple
add_library(simple INTERFACE IMPORTED)

set_target_properties(simple PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SIMPLE_LIBRARY_EXPORT"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Jack/Repo/simple/include"
  INTERFACE_LINK_LIBRARIES "zmq;zmq;simple_msgs"
)

# Create imported target simple_msgs
add_library(simple_msgs SHARED IMPORTED)

# Import target "simple_msgs" for configuration "Debug"
set_property(TARGET simple_msgs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(simple_msgs PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/Jack/Repo/simple/build2017/msgs/Debug/simple_msgs.lib"
  IMPORTED_LOCATION_DEBUG "C:/Users/Jack/Repo/simple/build2017/msgs/Debug/simple_msgs.dll"
  )

# Import target "simple_msgs" for configuration "Release"
set_property(TARGET simple_msgs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(simple_msgs PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/Jack/Repo/simple/build2017/msgs/Release/simple_msgs.lib"
  IMPORTED_LOCATION_RELEASE "C:/Users/Jack/Repo/simple/build2017/msgs/Release/simple_msgs.dll"
  )

# Import target "simple_msgs" for configuration "MinSizeRel"
set_property(TARGET simple_msgs APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(simple_msgs PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/Jack/Repo/simple/build2017/msgs/MinSizeRel/simple_msgs.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Jack/Repo/simple/build2017/msgs/MinSizeRel/simple_msgs.dll"
  )

# Import target "simple_msgs" for configuration "RelWithDebInfo"
set_property(TARGET simple_msgs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(simple_msgs PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/Jack/Repo/simple/build2017/msgs/RelWithDebInfo/simple_msgs.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Jack/Repo/simple/build2017/msgs/RelWithDebInfo/simple_msgs.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
