#pragma once

#include <ostream>
#include "generic_message.h"
#include "generated/bool_generated.h"

namespace simple_msgs
{
class Bool : public GenericMessage
{
public:
  Bool();
  Bool(bool);
  Bool(const uint8_t*);
  Bool(const Bool&);
  Bool(Bool&&);

  Bool& operator=(const Bool&);
  Bool& operator=(Bool&&);
  Bool& operator=(const uint8_t* data);

  inline bool operator==(const Bool& rhs) const { return (data_ == rhs.data_); }
  inline bool operator!=(const Bool& rhs) const { return !(*this == rhs); }

  inline Bool& operator!()
  {
    data_ = !data_;
    return *this;
  }

  friend std::ostream& operator<<(std::ostream& out, const Bool& b);

  /**
   * @brief Builds and returns the buffer accordingly to the values currently stored.
   * @return the buffer data.
   */
  uint8_t* getBufferData() const;

  /**
   * @brief Set the boolean value.
   */
  void set(bool data);

  /**
   * @brief Get the boolean value.
   */
  bool get() const { return data_; }

  /**
   * @brief Returns an identifier of the message type generated by the flatbuffers.
   */
  static inline const char* getTopic() { return BoolFbsIdentifier(); }

private:
  bool data_{false};
};
}  // Namespace simple_msgs.
