/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy
 * Langsch - fernanda.langsch@tum.de
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef SIMPLE_MSGS_DOUBLE_H
#define SIMPLE_MSGS_DOUBLE_H

#include "generated/double_generated.h"
#include "numeric_type.hpp"

// Specialized functions for NumericType<double>.

namespace simple_msgs {

//! Typedef for Double messages.
using Double = NumericType<double>;

/**
 * @brief Construct a Double message using a raw memory coming from network.
 */
template <>
inline NumericType<double>::NumericType(const void* data) : data_{GetDoubleFbs(data)->data()} {}

/**
 * @brief Copy assignment operator that uses raw memory coming from the network.
 */
template <>
NumericType<double>& NumericType<double>::operator=(std::shared_ptr<void*> rhs) {
  data_.store(GetDoubleFbs(*rhs)->data());
  return *this;
}

/**
 * @brief Builds and returns the buffer accordingly to the value currently stored.
 */
template <>
std::shared_ptr<flatbuffers::DetachedBuffer> NumericType<double>::getBufferData() const {
  flatbuffers::FlatBufferBuilder builder{1024};
  DoubleFbsBuilder tmp_builder{builder};
  tmp_builder.add_data(data_.load());
  FinishDoubleFbsBuffer(builder, tmp_builder.Finish());
  return std::make_shared<flatbuffers::DetachedBuffer>(builder.Release());
}

/**
 * @brief Returns an identifier of the message type generated by the flatbuffers.
 */
template <>
inline std::string NumericType<double>::getTopic() {
  return DoubleFbsIdentifier();
}
}  // Namespace simple_msgs.

#endif  // SIMPLE_MSGS_DOUBLE_H
