/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy Langsch - fernanda.langsch@tum.de
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser Public License for more details.
 *
 * You should have received a copy of the GNU Lesser Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef SIMPLE_MSGS_HOMO_MATRIX_H
#define SIMPLE_MSGS_HOMO_MATRIX_H

#include <array>
#include <ostream>
#include "generated/homo_matrix_generated.h"
#include "generic_message.h"
#include "point.h"
#include "rotation_matrix.h"

namespace simple_msgs {
/**
 * @brief Point: wrapper class around the PointFbs generated code from flatbuffers.
 */
class HomoMatrix : public GenericMessage {
public:
  HomoMatrix() = default;
  HomoMatrix(const Point&, const RotationMatrix&);
  HomoMatrix(Point&&, RotationMatrix&&);
  HomoMatrix(const void*);
  HomoMatrix(const HomoMatrix&);
  HomoMatrix(HomoMatrix&&) noexcept;

  HomoMatrix& operator=(const HomoMatrix&);
  HomoMatrix& operator=(HomoMatrix&&) noexcept;
  HomoMatrix& operator=(std::shared_ptr<void*>);

  inline bool operator==(const HomoMatrix& rhs) const { return (point_ == rhs.point_ && matrix_ == rhs.matrix_); }
  inline bool operator!=(const HomoMatrix& rhs) const { return !(*this == rhs); }
  friend std::ostream& operator<<(std::ostream&, const HomoMatrix&);

  /**
   * @brief Builds and returns the buffer accordingly to the values currently stored.
   * @return the buffer data.
   */
  std::shared_ptr<flatbuffers::DetachedBuffer> getBufferData() const override;

  inline RotationMatrix& getRotationMatrix() { return matrix_; }
  inline const RotationMatrix& getRotationMatrix() const { return matrix_; }

  inline Point& getPoint() { return point_; }
  inline const Point& getPoint() const { return point_; }

  void setPoint(const Point&);
  void setRotationMatrix(const RotationMatrix&);

  /**
   * @brief Returns an identifier of the message type generated by the flatbuffers.
   */
  static inline std::string getTopic() { return HomoMatrixFbsIdentifier(); }

private:
  Point point_{};
  RotationMatrix matrix_{};
};
}  // Namespace simple_msgs.

#endif  // SIMPLE_MSGS_POINT_STAMPED_H
