#pragma once

#include <algorithm>
#include <ostream>
#include "numeric_type.hpp"
#include "header.h"
#include "generic_message.h"

namespace simple_msgs
{
template <typename T>
class NumericTypeStamped : public GenericMessage
{
public:
  // Constructors.

	NumericTypeStamped()
    : GenericMessage()
  {
  }

	NumericTypeStamped(T data)
    : GenericMessage()
    , data_(data)
  {
  }

  /**
   * @brief Constructor from the buffer data, implementation is specific to the template specialization.
   */
	NumericTypeStamped(const uint8_t* data);

  // Copy operations.

	NumericTypeStamped(const NumericTypeStamped& other)
    : NumericTypeStamped(other.data_)
  {
  }

	NumericTypeStamped& operator=(const NumericTypeStamped& rhs)
  {
    std::lock_guard<std::mutex> lock(mutex_);
    std::swap(data_, rhs.data_);
    modified_ = true;
    return *this;
  }

  // Move operations.

	NumericTypeStamped(NumericType&& other)
    : NumericTypeStamped(std::move(other.data_))
  {
  }

	NumericTypeStamped& operator=(NumericTypeStamped&& rhs)
  {
    std::lock_guard<std::mutex> lock(mutex_);
    data_ = std::move(rhs.data_);
    modified_ = true;
    return *this;
  }

  // Relational operators.
  inline bool operator==(const NumericTypeStamped& rhs) { return data_ == rhs.data_; }
  inline bool operator!=(const NumericTypeStamped& rhs) { return !(*this == rhs); }
  inline bool operator<(const NumericTypeStamped& rhs) { return data_ < rhs.data_; }
  inline bool operator>(const NumericTypeStamped& rhs) { return rhs < *this; }
  inline bool operator<=(const NumericTypeStamped& rhs) { return !(*this > rhs); }
  inline bool operator>=(const NumericTypeStamped& rhs) { return !(*this < rhs); }
  // Increment and decrement operators.

  NumericTypeStamped& operator--()
  {
    --data_;
    return *this;
  }

  NumericTypeStamped operator--(int)
  {
    const NumericType old(*this);
    --(*this);
    return old;
  }

  NumericTypeStamped& operator++()
  {
    ++data_;
    return *this;
  }

  NumericTypeStamped operator++(int)
  {
    const NumericType old(*this);
    ++(*this);
    return old;
  }

  // Binary arithmetic operatorss

  NumericTypeStamped& operator+=(const NumericTypeStamped& rhs)
  {
    data_ += rhs.data_;
    return *this;
  }

  friend NumericTypeStamped operator+(NumericTypeStamped lhs, const NumericTypeStamped& rhs)
  {
    lhs += rhs;
    return lhs;
  }

  NumericTypeStamped& operator-=(const NumericTypeStamped& rhs)
  {
    data_ -= rhs.data_;
    return *this;
  }

  friend NumericTypeStamped operator-(NumericTypeStamped lhs, const NumericTypeStamped& rhs)
  {
    lhs -= rhs;
    return lhs;
  }

  NumericTypeStamped& operator*=(const NumericTypeStamped& rhs)
  {
    data_ *= rhs.data_;
    return *this;
  }

  friend NumericTypeStamped operator*(NumericTypeStamped lhs, const NumericTypeStamped& rhs)
  {
    lhs *= rhs;
    return lhs;
  }

  NumericTypeStamped& operator/=(const NumericTypeStamped& rhs)
  {
    data_ /= rhs.data_;
    return *this;
  }

  friend NumericTypeStamped operator/(NumericTypeStamped lhs, const NumericTypeStamped& rhs)
  {
    lhs /= rhs;
    return lhs;
  }

  /**
   * @brief Builds and returns the buffer accordingly to the values currently stored.
   * @return the buffer data.
   */
  uint8_t* getBufferData() const;

  /**
   * @brief Set the double value.
   */
  void set(T data);

  /**
   * @brief Get the double value.
   */
  T get() const { return data_; }
  /**
   * @brief Returns an identifier of the message type generated by the flatbuffers.
   */
  static inline const char* getTopic();

  //  Stream extraction.
  template <typename Tn>
  friend std::ostream& operator<<(std::ostream& out, const NumericTypeStamped<Tn>& obj);

private:
  T data_{0};
};

template <typename T>
std::ostream& operator<<(std::ostream& out, const NumericTypeStamped<T>& obj)
{
  out << obj.data_;
  return out;
}
}  // Namespace simple_msgs.
