/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy
 * Langsch - fernanda.langsch@tum.de
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef SIMPLE_MSGS_POSE_STAMPED_H
#define SIMPLE_MSGS_POSE_STAMPED_H

#include <mutex>
#include <ostream>

#include "header.hpp"
#include "pose.hpp"

namespace simple_msgs {
/**
 * @class PoseStamped pose_stamped.hpp.
 * @brief Thread-safe wrapper for a Flatbuffers PoseStamped message.
 * It contains a Pose and a Header message.
 */
class PoseStamped : public GenericMessage {
public:
  PoseStamped() = default;

  /**
   * @brief Construct a PoseStamped message given its Header and Pose.
   */
  PoseStamped(const Header& header, const Pose& pose);

  /**
   * @brief Construct a PoseStamped message given its Header and Pose.
   */
  PoseStamped(Header&& header, Pose&& pose);

  /**
   * @brief Copy constructor.
   */
  PoseStamped(const PoseStamped& other);

  /**
   * @brief Move constructor.
   */
  PoseStamped(PoseStamped&& other) noexcept;

  /**
   * @brief Copy assignment operator.
   */
  PoseStamped& operator=(const PoseStamped& rhs);

  /**
   * @brief Move assignment operator.
   */
  PoseStamped& operator=(PoseStamped&& rhs) noexcept;

  /**
   * @brief Returns true if lhs is equal to rhs, false otherwise.
   */
  inline bool operator==(const PoseStamped& rhs) const {
    std::lock_guard<std::mutex> lock{mutex_};
    return (pose_ == rhs.pose_ && header_ == rhs.header_);
  }

  /**
   * @brief Returns true if lhs is not equal to rhs, false otherwise.
   */
  inline bool operator!=(const PoseStamped& rhs) const { return !(*this == rhs); }

  /**
   * @brief Stream extraction operator.
   */
  friend std::ostream& operator<<(std::ostream& out, const PoseStamped& p);

  /**
   * @brief Returns message Header.
   */
  inline Header& getHeader() {
    std::lock_guard<std::mutex> lock{mutex_};
    return header_;
  }

  /**
   * @brief Returns message Header.
   */
  inline const Header& getHeader() const {
    std::lock_guard<std::mutex> lock{mutex_};
    return header_;
  }

  /**
   * @brief Returns the message Pose.
   */
  inline Pose& getPose() {
    std::lock_guard<std::mutex> lock{mutex_};
    return pose_;
  }

  /**
   * @brief Returns the message Pose.
   */
  inline const Pose& getPose() const {
    std::lock_guard<std::mutex> lock{mutex_};
    return pose_;
  }

  /**
   * @brief Modifies the message Header.
   */
  void setHeader(const Header& header);

  /**
   * @brief Modifies the message Pose.
   */
  void setPose(const Pose& pose);

  /**
   * @brief Returns an identifier of the message type generated by the flatbuffers.
   */
  static std::string getTopic();

protected:
  /**
   * @brief Construct a PoseStamped message using a raw memory coming from network.
   */
  PoseStamped(const void* data);

  /**
   * @brief Copy assignment operator that uses raw memory coming from the network.
   */
  PoseStamped& operator=(std::shared_ptr<void*> rhs) override;

  /**
   * @brief Builds and returns the buffer accordingly to the values currently stored.
   */
  std::shared_ptr<flatbuffers::DetachedBuffer> getBufferData() const override;

private:
  //! Thread safe copy and move constructors.
  PoseStamped(const PoseStamped& other, const std::lock_guard<std::mutex>&);
  PoseStamped(PoseStamped&& other, const std::lock_guard<std::mutex>&) noexcept;

  mutable std::mutex mutex_{};
  Header header_{};
  Pose pose_{};
};
}  // Namespace simple_msgs.

#endif  // SIMPLE_MSGS_POSE_STAMPED_H
