/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy
 * Langsch - fernanda.langsch@tum.de
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef SIMPLE_MSGS_POSE_H
#define SIMPLE_MSGS_POSE_H

#include <mutex>
#include <ostream>

#include "point.hpp"
#include "quaternion.hpp"

namespace simple_msgs {
/**
 * @class Pose pose.hpp.
 * @brief Thread-safe wrapper for a Flatbuffers Pose message.
 * It represents a Pose in 3D space by its position and orientation.
 */
class Pose : public GenericMessage {
public:
  Pose() = default;

  /**
   * @brief Construct a Pose message given its position and orientation.
   */
  Pose(const Point& point, const Quaternion& quaternion);

  /**
   * @brief Construct a Pose message given its position and orientation.
   */
  Pose(Point&& point, Quaternion&& quaternion);

  /**
   * @brief Copy constructor.
   */
  Pose(const Pose& other);

  /**
   * @brief Move constructor.
   */
  Pose(Pose&& other) noexcept;

  /**
   * @brief Copy assignment operator.
   */
  Pose& operator=(const Pose& rhs);

  /**
   * @brief Move assignment operator.
   */
  Pose& operator=(Pose&& rhs) noexcept;

  /**
   * @brief Returns true if lhs is equal to rhs, false otherwise.
   */
  inline bool operator==(const Pose& rhs) const {
    std::lock_guard<std::mutex> lock{mutex_};
    return (position_ == rhs.position_ && quaternion_ == rhs.quaternion_);
  }

  /**
   * @brief Returns true if lhs is not equal to rhs, false otherwise.
   */
  inline bool operator!=(const Pose& rhs) const { return !(*this == rhs); }

  /**
   * @brief Stream extraction operator.
   */
  friend std::ostream& operator<<(std::ostream& out, const Pose& p);

  /**
   * @brief Returns the translational part of the Pose as a Point message.
   */
  inline Point& getPosition() {
    std::lock_guard<std::mutex> lock{mutex_};
    return position_;
  }

  /**
   * @brief Returns the translational part of the Pose as a Point message.
   */
  inline const Point& getPosition() const {
    std::lock_guard<std::mutex> lock{mutex_};
    return position_;
  }

  /**
   * @brief Returns the rotational part of the Pose as a Quaternion message.
   */
  inline Quaternion& getQuaternion() {
    std::lock_guard<std::mutex> lock{mutex_};
    return quaternion_;
  }

  /**
   * @brief Returns the rotational part of the Pose as a Quaternion message.
   */
  inline const Quaternion& getQuaternion() const {
    std::lock_guard<std::mutex> lock{mutex_};
    return quaternion_;
  }

  /**
   * @brief Modifies the rotational part of the Pose.
   */
  void setPosition(const Point& position);

  /**
   * @brief Modifies the translational part of the Pose.
   */
  void setQuaternion(const Quaternion& quaternion);

  /**
   * @brief Returns an identifier of the message type generated by the flatbuffers.
   */
  static std::string getTopic();

protected:
  /**
   * @brief Construct a Pose message using a raw memory coming from network.
   */
  explicit Pose(const void* data);

  /**
   * @brief Copy assignment operator that uses raw memory coming from the network.
   */
  Pose& operator=(std::shared_ptr<void*> rhs) override;

  /**
   * @brief Builds and returns the buffer accordingly to the values currently stored.
   */
  std::shared_ptr<flatbuffers::DetachedBuffer> getBufferData() const override;

  friend class PoseStamped;
  template <typename T>
  friend class Image;

private:
  //! Thread safe copy and move constructors.
  Pose(const Pose& other, const std::lock_guard<std::mutex>&);
  Pose(Pose&& other, const std::lock_guard<std::mutex>&) noexcept;

  mutable std::mutex mutex_{};
  Point position_{};
  Quaternion quaternion_{};
};
}  // Namespace simple_msgs.

#endif  // SIMPLE_MSGS_POSE_H
