/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy Langsch - fernanda.langsch@tum.de
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser Public License for more details.
 *
 * You should have received a copy of the GNU Lesser Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef SIMPLE_MSGS_QUATERNION_STAMPED_H
#define SIMPLE_MSGS_QUATERNION_STAMPED_H

#include <array>
#include <ostream>

#include "generated/quaternion_stamped_generated.h"
#include "generic_message.h"
#include "header.h"
#include "quaternion.h"

namespace simple_msgs {
/**
 * @class QuaternionStamped quaternion_stamped.h.
 * @brief Wrapper for a Flatbuffers QuaternionStamped message.
 * It contains a Quaternion and a Header message.
 */
class QuaternionStamped : public GenericMessage {
public:
  QuaternionStamped() = default;

  /**
   * @brief Construct a QuaternionStamped message given its Header and Quaternion.
   */
  QuaternionStamped(const Header&, const Quaternion&);

  /**
   * @brief Construct a QuaternionStamped message given its Header and Quaternion.
   */
  QuaternionStamped(Header&&, Quaternion&&);

  /**
   * @brief Construct a QuaternionStamped message using a raw memory coming from network.
   */
  QuaternionStamped(const void*);

  /**
   * @brief Copy constructor.
   */
  QuaternionStamped(const QuaternionStamped&);

  /**
   * @brief Move constructor.
   */
  QuaternionStamped(QuaternionStamped&&) noexcept;

  /**
   * @brief Copy assignment operator.
   */
  QuaternionStamped& operator=(const QuaternionStamped&);

  /**
   * @brief Move assignment operator.
   */
  QuaternionStamped& operator=(QuaternionStamped&&) noexcept;

  /**
   * @brief Copy assignment operator that uses raw memory coming from the network.
   */
  QuaternionStamped& operator=(std::shared_ptr<void*>);

  /**
   * @brief Returns true if lhs is equal to rhs, false otherwise.
   */
  inline bool operator==(const QuaternionStamped& rhs) const {
    return (quaternion_ == rhs.quaternion_ && header_ == rhs.header_);
  }

  /**
   * @brief Returns true if lhs is not equal to rhs, false otherwise.
   */
  inline bool operator!=(const QuaternionStamped& rhs) const { return !(*this == rhs); }

  /**
   * @brief Stream extraction operator.
   */
  friend std::ostream& operator<<(std::ostream&, const QuaternionStamped&);

  /**
   * @brief Builds and returns the buffer accordingly to the values currently stored.
   */
  std::shared_ptr<flatbuffers::DetachedBuffer> getBufferData() const override;

  /**
   * @brief Returns the message Hader.
   */
  inline Header& getHeader() { return header_; }

  /**
   * @brief Returns the message Hader.
   */
  inline const Header& getHeader() const { return header_; }

  /**
   * @brief Returns the message Quaternion.
   */
  inline Quaternion& getQuaternion() { return quaternion_; }

  /**
   * @brief Returns the message Quaternion.
   */
  inline const Quaternion& getQuaternion() const { return quaternion_; }

  /**
   * @brief Modifies the message Header.
   */
  void setHeader(const Header&);

  /**
   * @brief Modifies the message Quaternion.
   */
  void setQuaternion(const Quaternion&);

  /**
   * @brief Returns an identifier of the message type generated by the flatbuffers.
   */

  static inline std::string getTopic() { return QuaternionStampedFbsIdentifier(); }

private:
  Header header_{};
  Quaternion quaternion_{};
};
}  // Namespace simple_msgs.

#endif  // SIMPLE_MSGS_QUATERNION_STAMPED_H
