/**
 * S.I.M.P.L.E. - Smart Intuitive Messaging Platform with Less Effort
 * Copyright (C) 2018 Salvatore Virga - salvo.virga@tum.de, Fernanda Levy Langsch - fernanda.langsch@tum.de
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser Public License for more details.
 *
 * You should have received a copy of the GNU Lesser Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef SIMPLE_MSGS_TRANSFORM_STAMPED_H
#define SIMPLE_MSGS_TRANSFORM_STAMPED_H

#include <array>
#include <ostream>

#include "generated/transform_stamped_generated.h"
#include "header.h"
#include "transform.h"

namespace simple_msgs {
/**
 * @class TransformStamped transform_stamped.h.
 * @brief Thread-safe wrapper for a Flatbuffers TransformStamped message.
 * It contains a Transform and a Header message.
 */
class TransformStamped : public GenericMessage {
public:
  TransformStamped() = default;

  /**
   * @brief Construct a TransformStamped message given its Header and Transform.
   */
  TransformStamped(const Header&, const Transform&);

  /**
   * @brief Construct a TransformStamped message given its Header and Transform.
   */
  TransformStamped(Header&&, Transform&&);

  /**
   * @brief Construct a TransformStamped message using a raw memory coming from network.
   */
  TransformStamped(const void*);

  /**
   * @brief Copy constructor.
   */
  TransformStamped(const TransformStamped&);

  /**
   * @brief Move constructor.
   */
  TransformStamped(TransformStamped&&) noexcept;

  /**
   * @brief Copy assignment operator.
   */
  TransformStamped& operator=(const TransformStamped&);

  /**
   * @brief Move assignment operator.
   */
  TransformStamped& operator=(TransformStamped&&) noexcept;

  /**
   * @brief Copy assignment operator that uses raw memory coming from the network.
   */
  TransformStamped& operator=(std::shared_ptr<void*>);

  /**
   * @brief Returns true if lhs is equal to rhs, false otherwise.
   */
  inline bool operator==(const TransformStamped& rhs) const {
    std::lock_guard<std::mutex> lock{mutex_};
    return (transform_ == rhs.transform_ && header_ == rhs.header_);
  }

  /**
   * @brief Returns true if lhs is not equal to rhs, false otherwise.
   */
  inline bool operator!=(const TransformStamped& rhs) const { return !(*this == rhs); }

  /**
   * @brief Stream extraction operator.
   */
  friend std::ostream& operator<<(std::ostream&, const TransformStamped&);

  /**
   * @brief Builds and returns the buffer accordingly to the values currently stored.
   */
  std::shared_ptr<flatbuffers::DetachedBuffer> getBufferData() const override;

  /**
   * @brief Returns the message Header.
   */
  inline Header& getHeader() {
    std::lock_guard<std::mutex> lock{mutex_};
    return header_;
  }

  /**
   * @brief Returns the message Header.
   */
  inline const Header& getHeader() const {
    std::lock_guard<std::mutex> lock{mutex_};
    return header_;
  }

  /**
   * @brief Returns the message Transform.
   */
  inline Transform& getTransform() {
    std::lock_guard<std::mutex> lock{mutex_};
    return transform_;
  }

  /**
   * @brief Returns the message Transform.
   */
  inline const Transform& getTransform() const {
    std::lock_guard<std::mutex> lock{mutex_};
    return transform_;
  }

  /**
   * @brief Modifies the message header.
   */
  void setHeader(const Header&);

  /**
   * @brief Modifies the message Transform.
   */
  void setTransform(const Transform&);

  /**
   * @brief Returns an identifier of the message type generated by the flatbuffers.
   */
  static inline std::string getTopic() { return TransformStampedFbsIdentifier(); }

private:
  //! Thread safe copy and move constructors.
  TransformStamped(const TransformStamped& other, const std::lock_guard<std::mutex>&);
  TransformStamped(TransformStamped&& other, const std::lock_guard<std::mutex>&) noexcept;

  mutable std::mutex mutex_{};
  Header header_{};
  Transform transform_{};
};
}  // Namespace simple_msgs.

#endif  // SIMPLE_MSGS_TRANSFORM_STAMPED_H
